export enum TypographyProperties {
  FONT_FAMILY = 'Font',
  FONT_WEIGHT = 'Weight',
  FONT_SIZE = 'Size',
  LINE_HEIGHT = 'Height',
  COLOR = 'Color',
  TEXT_ALIGN = 'Align',
  STYLE = 'Style',
  FONT_STYLE = 'Italic',
  TEXT_DECORATION = 'Decoration',
  SPACING = 'Spacing',
  LETTER_SPACING = 'Letter',
  WORD_SPACING = 'Word',
  TEXT_TRANSFORM = 'Transform',
  WORD_WRAP = 'Wrap',
  BREAKING = 'Breaking',
  WORD_BREAK = 'Words',
  WHITE_SPACE = 'Lines',
}
export enum TypographyProperties {
  FONT_FAMILY = 'font-family',
  FONT_WEIGHT = 'font-weight',
  FONT_SIZE = 'font-size',
  LINE_HEIGHT = 'line-height',
  COLOR = 'color',
  TEXT_ALIGN = 'text-align',
  FONT_STYLE = 'font-style',
  TEXT_DECORATION = 'text-decoration',
  LETTER_SPACING = 'letter-spacing',
  WORD_SPACING = 'word-spacing',
  TEXT_TRANSFORM = 'text-transform',
  WORD_WRAP = 'word-wrap',
  WORD_BREAK = 'word-break',
  WHITE_SPACE = 'white-space',
}

export const TypographyValues = {
  [TypographyProperties.FONT_FAMILY]: 'f',
  [TypographyProperties.FONT_WEIGHT]: 'w',
  [TypographyProperties.FONT_SIZE]: 's',
  [TypographyProperties.LINE_HEIGHT]: 'lh',
  [TypographyProperties.COLOR]: 'c',
  [TypographyProperties.TEXT_ALIGN]: 'a',
  [TypographyProperties.FONT_STYLE]: 'fs',
  [TypographyProperties.TEXT_DECORATION]: 'dec',
  [TypographyProperties.LETTER_SPACING]: 'ls',
  [TypographyProperties.WORD_SPACING]: 'ws',
  [TypographyProperties.TEXT_TRANSFORM]: 'ttr',
  [TypographyProperties.WORD_WRAP]: 'wwr',
  [TypographyProperties.WORD_BREAK]: 'wbr',
  [TypographyProperties.WHITE_SPACE]: 'whs',
}

export const mapPropertyTitle = {
  [TypographyProperties.FONT_FAMILY]: 'Font',
  [TypographyProperties.FONT_WEIGHT]: 'Weight',
  [TypographyProperties.FONT_SIZE]: 'Size',
  [TypographyProperties.LINE_HEIGHT]: 'Height',
  [TypographyProperties.COLOR]: 'Color',
  [TypographyProperties.TEXT_ALIGN]: 'Align',
  [TypographyProperties.FONT_STYLE]: 'Italic',
  [TypographyProperties.TEXT_DECORATION]: 'Decoration',
  [TypographyProperties.LETTER_SPACING]: 'Letter',
  [TypographyProperties.WORD_SPACING]: 'Word',
  [TypographyProperties.TEXT_TRANSFORM]: 'Transform',
  [TypographyProperties.WORD_WRAP]: 'Wrap',
  [TypographyProperties.WORD_BREAK]: 'Words',
  [TypographyProperties.WHITE_SPACE]: 'Lines',
}
